version: '2'
services:
  service: # Main
    build: .
    environment:
      NODE_ENV: 'development'
      TOKEN: 'githubtokenhere'
      USERNAME: 'zappen999'
      SLACK_TOKEN: 'slacktokenhere'
      SLACK_USER: '@yourusernamehere'
      BOT_NAME: 'Slackbot'
    volumes:
      - ./src:/home/node/app/src
      - ./scripts:/home/node/app/scripts
      - ./package.json:/home/node/app/package.json
      - ./.nycrc:/home/node/app/.nycrc
      - ./coverage:/home/node/app/coverage
    ports:
      - 9222:9222
